--=========================================================================================---
--=====================Mouse Bind Keys / Keyboard bind Keys (only logiitech)==========================---

--======== Rifles ========--
local Phantom =  nil
local Phantom_Keyboard = nil
local Vandal = nil
local Vandal_Keyboard = 2
local Bulldog = nil
local Bulldog_Keyboard = nil
--======== SMGs ========--
local Spectre = nil
local Spectre_Keyboard = nil
local Stinger = nil
local Stinger_Keyboard = nil
--======== SideArm ========--
local Frenzy = nil
local Frenzy_Keyboard = nil
--======== Heavy ========--
local Ares = nil
local Ares_Keyboard = nil
local Odin = nil
local Odin_Keyboard = nil
--========================================================================================---

EnablePrimaryMouseButtonEvents(true);
local recoil = falseB
local weapon = 0
function OnEvent(event, arg)
 if (event == "MOUSE_BUTTON_PRESSED" and arg == Phantom) or
(event == "G_PRESSED" and arg == Phantom_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Phantom\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Phantom\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
 elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Vandal) or
(event == "G_PRESSED" and arg == Vandal_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Vandal\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Vandal\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Stinger) or
(event == "G_PRESSED" and arg == Stinger_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Stinger\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Stinger\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Frenzy) or
(event == "G_PRESSED" and arg == Frenzy_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Frenzy\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Frenzy\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
 elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Spectre) or
(event == "G_PRESSED" and arg == Spectre_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Spectre\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Spectre\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Ares) or
(event == "G_PRESSED" and arg == Ares_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Ares\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Ares\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Odin) or
(event == "G_PRESSED" and arg == Odin_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Odin\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Odin\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
 elseif (event == "MOUSE_BUTTON_PRESSED" and arg == Bulldog) or
(event == "G_PRESSED" and arg == Bulldog_Keyboard) then
    recoil = not recoil
    weapon = arg
    if (recoil == false) then
      OutputLogMessage("OFF-Macro-Bulldog\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("ON-NoRecoil-Bulldog\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
end
end
end

-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
   if weapon == Phantom or weapon == Phantom_Keyboard then
if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,8)
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,8)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(11,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(10,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(-11,0)
        Sleep(24)
        MoveMouseRelative(0,0) 
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-10,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
 until not IsMouseButtonPressed(1)
     end
-----------------------------------------------------------------------------------------------------
   elseif weapon == Ares or weapon == Ares_Keyboard then
if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,3)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(-3,3)
        Sleep(24)
        MoveMouseRelative(-2,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(-2,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(5,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(4,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2) -- ---
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0.1)
        Sleep(24)
        MoveMouseRelative(0,0.1)
        Sleep(24)
        MoveMouseRelative(0,0.1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,-1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,-1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,-1)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2) -- --
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
until not IsMouseButtonPressed(1)
     end
--------------------------------------------------------------------------------------------
  elseif weapon == Odin or weapon == Odin_Keyboard then
if recoil then
repeat
        Sleep(24)
if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        MoveMouseRelative(0,5)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(-5,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(-4,8)
        Sleep(24)
        MoveMouseRelative(0,8)
        Sleep(24)
        MoveMouseRelative(0,8)
        Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(6,3)
        Sleep(24)
        MoveMouseRelative(4,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(6,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2) -- ---
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-6,2)
        Sleep(24)
        MoveMouseRelative(-6,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
until not IsMouseButtonPressed(1)
     end
--------------------------------------------------------------------------------------------
   elseif weapon == Frenzy or weapon == Frenzy_Keyboard then
if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(-2,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(-2,8)
        Sleep(24)
        MoveMouseRelative(0,8)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(-2,5)
        Sleep(24)
        MoveMouseRelative(-2,6)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(1,0)
        Sleep(24)
        MoveMouseRelative(1,0)
        Sleep(24)
        MoveMouseRelative(1,0)
        Sleep(24)
        MoveMouseRelative(1,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(3,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(5,0.2)
        Sleep(24)
        MoveMouseRelative(3,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2) -- ---
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(-1,1)
        Sleep(24)
        MoveMouseRelative(-3,1)
        Sleep(24)
        MoveMouseRelative(-5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-5,1)
        Sleep(24)
        MoveMouseRelative(-2,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
       until not IsMouseButtonPressed(1)
     end
----------------------------------------
 elseif weapon == Vandal or weapon ==Vandal_Keyboard then
       if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,8)
        Sleep(24)
        MoveMouseRelative(0,9)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,8)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(4,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(4,0)
        Sleep(24)
        MoveMouseRelative(5,0)
        Sleep(24)
        MoveMouseRelative(5,0)
        Sleep(24)
        MoveMouseRelative(4,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-5,1)
        Sleep(24)
        MoveMouseRelative(-5,0)
        Sleep(24)
        MoveMouseRelative(-6,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- ---
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) -- --
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
       until not IsMouseButtonPressed(1)
end
------------------------------------------------------------------------------------------------
elseif weapon == Stinger or weapon == Stinger_Keyboard then
  if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,7)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,2)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(2,1)
        Sleep(24)
        MoveMouseRelative(2,1)
        Sleep(24)
        MoveMouseRelative(2,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(3,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(3,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(6,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(5,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
       MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-3,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-3,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
       MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(-7,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(-6,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
        Sleep(24)
        MoveMouseRelative(0,0.5)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        until not IsMouseButtonPressed(1)
end
---------------------------------------------------------------------------------------------
elseif weapon == Bulldog or weapon == Bulldog_Keyboard then
   if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(6,0)
        Sleep(24)
        MoveMouseRelative(6,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(-4,0.1)
        Sleep(24)
        MoveMouseRelative(-4,0.1)
        Sleep(24)
        MoveMouseRelative(-4,0.1)
        Sleep(24)
        MoveMouseRelative(0,0.1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0) --- ---
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        until not IsMouseButtonPressed(1)
     end
--------------------------------------------------------------------------------
 elseif weapon == Spectre or weapon == Spectre_Keyboard then
  if recoil then
repeat
        Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,2)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,5)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(-3,4)---
        Sleep(24)
        MoveMouseRelative(-3,4)
        Sleep(24)
        MoveMouseRelative(-3,4)
        if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,3)
        Sleep(24)
        MoveMouseRelative(0,-2)
        Sleep(24)
        MoveMouseRelative(0,-2)
        Sleep(24)
        MoveMouseRelative(0,-2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(5,0)
        Sleep(24)
        MoveMouseRelative(6,0)
        Sleep(24)
        MoveMouseRelative(5,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-3,1)
        Sleep(24)
        MoveMouseRelative(-4,0)
        Sleep(24)
        MoveMouseRelative(-5,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
        Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
   until not IsMouseButtonPressed(1)
     end
----------------------------------------------------------------------------------------------
end
end